// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnTXB7TMIrOogvKr8XmYODEfIsRIyT9og',
    appId: '1:660306225395:android:e86d830f6944f91a03ef86',
    messagingSenderId: '660306225395',
    projectId: 'travel-community-marketplace',
    storageBucket: 'travel-community-marketplace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwJ6LcJ8ikKA7JXgCDb3e2ZnvXusEVKpY',
    appId: '1:660306225395:ios:7e29200bf490d32803ef86',
    messagingSenderId: '660306225395',
    projectId: 'travel-community-marketplace',
    storageBucket: 'travel-community-marketplace.firebasestorage.app',
    androidClientId: '660306225395-37rg5fu480604bp41svps0kejfac279j.apps.googleusercontent.com',
    iosClientId: '660306225395-f3ffeh5hkrcuijb2d247reuf6uls69bb.apps.googleusercontent.com',
    iosBundleId: 'com.mmc.tcm',
  );

}